---
- hosts: all
  gather_facts: no
  vars:
    proxy_version: 0.8.10
    ansible_path: ~/ansible/
    task_path: "{{ansible_path}}3proxy/"
    source_path: "{{task_path}}source/"
    app_path: "{{task_path}}bin/"
    compile_path: "{{source_path}}3proxy-{{proxy_version}}/"
    archive_path: "{{source_path}}source.tgz"
    download_url: "https://github.com/z3APA3A/3proxy/archive/{{proxy_version}}.tar.gz"
  tasks:
  - name: check that host is accessible
    ping:
  - name: create folder for ansible scripts
    file:
      path: "{{ansible_path}}"
      state: directory
  - name: create folder for executable
    file:
      path: "{{app_path}}"
      state: directory
  - name: create folder for task
    file:
      path: "{{task_path}}"
      state: directory
  - name: create source code folder
    file:
      path: "{{source_path}}"
      state: directory
  - name: download source code
    get_url:
      url: "{{download_url}}"
      dest: "{{archive_path}}"
  - name: unpack source code
    unarchive:
      remote_src: yes
      src: "{{archive_path}}"
      dest: "{{source_path}}"
  - name: compile source code
    make:
      chdir: "{{compile_path}}"
      file: Makefile.Linux #TODO сделать контексто-зависимым
  - name: copy executable to required place
    copy:
      dest: "{{app_path}}"
      src: "{{compile_path}}/src/3proxy"
      remote_src: yes
  - name: create system group
    group:
      name: proxy3
      system: yes
    become: yes
  - name: create system user
    user:
      name: proxy3
      group: proxy3
      create_home: no
      system: yes
    become: yes
    register: userinfo
  - debug: var=userinfo
  - set_fact:
      user_id: "{{userinfo.uid}}"
      group_id: "{{userinfo.group}}"
  - debug: var=user_id
  - debug: var=group_id
